BUCKET_NAME = "hack-bucket25"
CHUNK_DURATION_SECONDS = 15
PINECONE_INDEX_NAME = "video-clips"
PINECONE_NAMESPACE = "clips"
EMBEDDING_DIMENSION = 1536
PRESIGNED_URL_EXPIRY_SECONDS = 3600

VIDEO_CHUNK_FORMAT = "mp4"
TEMP_DIR = "/tmp"

GCS_ENDPOINT_URL = "https://storage.googleapis.com"